### ISSUE TITLE
Drug 영어 이름 crawling

### ISSUE THREAD

**Issue by chandryou** [OHDSI/EdiToOmop#11]
Drug 영어 이름 crawling
(심평원 API or 식약처 이용)

https://github.com/ABMI/webCrawlingClass/blob/master/document/%5BRC%204%EA%B8%B0%5D%207%ED%9A%8C%EC%B0%A8%20%EA%B0%95%EC%9D%98%EC%95%88.pdf 
참조

**Comment by ycseong07** [comment]
use drug ingredient name as concept name
