### ISSUE TITLE
EDI 코드 내 다양한 코드 시스템 현황 파악

### ISSUE THREAD

**Issue by chandryou** [OHDSI/EdiToOmop#18]
전자문서교환을 이용한 건강보험진료비청구코드인 EDI 코드는 다양한 의료 서비스를 나타내는데(의․치과에 한해 수가코드, 의약품코드, 보험등재약 일반명코드, 치료재료 코드, 공상코드로 나뉘어 분류되고 있음), 각 자리 수와 자리에 해당하는 문자의 의미가 다양하며 시간의 흐름에 따라 형태가 바뀌어옴. 따라서 EDI 코드의 형태에 따라 표현하는 방식을 조사하여 정리하고자 함

**Comment by ycseong07** [comment]
해당 내용 포함한 결과보고서 제출
