### ISSUE TITLE
OMOP 코드 체계에 대한 조사

### ISSUE THREAD

**Issue by chandryou** [OHDSI/EdiToOmop#19]
OMOP 코드는 OMOP CDM에서 하나의 임상사건을 나타내기 위해 부여되는 최소의 단위이며(concept이라고 함), 각 OMOP 코드는 서로에 대한 관계 혹은 수직적인 계층 역시 명시되어 있음. 현재 국내에서는 이와 같은 온톨로지 체계를 적용한 사례를 파악하고 적용한 경우를 찾아보기 힘들기 때문에 이에 대한 포괄적인 정보를 정리하고자 함

**Comment by ycseong07** [comment]
해당 내용 포함한 결과보고서 제출
