### ISSUE TITLE
향후 운영 관리 매뉴얼에 수정 및 건의사항에 대한 프로세스/창구 언급 필요

### ISSUE THREAD

**Issue by chandryou** [OHDSI/EdiToOmop#30]
향후 운영 관리 매뉴얼에 수정 및 건의사항에 대한 프로세스/창구 언급 필요
> OMOP vocabulary GitHub 또는 Forum을 안내해주면 되지 않을까 싶음.

**Comment by ycseong07** [comment]
해당 내용을 포함안 결과보고서 제출
